### ISSUE TITLE
Mustard VS RegEx

### ISSUE THREAD

**Issue by eonist** [mathewsanders/Mustard#8]
I'm Trying to understand Mustard. So I tried to do your example: 
https://github.com/mathewsanders/Mustard/blob/master/Documentation/Template%20tokenizer.md

In Swift RegEx
```swift
let str = "Serial: #YF 1942-b 12/01/17 (Scanned) 12/03/17 (Arrived) ref: 99/99/99"
let usDatePattern:String = "(\\d\\d)[-\\/](\\d\\d)[-\\/](\\d\\d(?:\\d\\d)?)"//Must be in the format: 12-30-1968 (mm-dd-yyyy) works with: "12-30-1968" and "12/30/1968" syntax
let matches = str.matches(usDatePattern)//RegExpMatch.datePattern
matches.forEach {
    let month:String = $0.value(str, 1)
    let day:String = $0.value(str, 2)
    let year:String = $0.value(str, 3)
    let dateStr:String = year + "/" + month + "/" + day
    let dateFormatter = DateFormatter()
    dateFormatter.dateFormat = "yy/mm/dd"
    let date:Date? = dateFormatter.date(from: dateStr)
    if date != nil {Swift.print(dateStr)}//Output: 17/12/01, 17/12/03
}
```

So mustard is more human readable than RegEx i guess. 
**Q1:** Do you see a use-case for mustard in Chat-bots, Ai-bot-writers etc?

**Q2:** Seems like you know a bit about string scanners having built Mustard. I've written a css parser in RegEx: [here](https://github.com/eonist/Element/blob/master/src/css/utils/CSSParser.swift) doing it in RegEx is probably not the ultimate solution. What should one use? Scanner, Mustard other?

**Comment by mathewsanders** [comment]
Good questions! 

I'm going to preface this with two things: 1. I'm about 10% comfortable writing regular expressions. I can use them for simple matches, but even with the date example you've given I would have searched for an existing solution rather than writing from scratch. 2. I have a mystical belief that regular expressions can probably do just about anything.

**A1**
To give some context... Mustard came to be as a response from this [code review](http://codereview.stackexchange.com/questions/150117/search-a-string-for-barcodes-but-ignore-certain-characters/151198#151198) which is looking for a way to find the code `YF1942B` but with the possibility that there might be other characters (spaces, hyphen, etc) within the target string.

The changes that I suggested based on some (much simpler) code that I'd written for pre-processing natural language input and as an exercise I decided to see if I could extend my existing simple code to create a more flexible system-- and Mustard is what came out of that.

I suspect that anything that can be done with Mustard can be performed faster with a regular expression.

My use case is a UI where people enter workout related information in plan text (example: _"10 reps front lunge 12.5lbs kettlebells"_ or _"3 min plank"_) and then allow people to interact with the input (e.g. tap on "min" in the second example and the text "3 min" is highlighted with the ability to increment the time +/- 30 or 60 second increments). 

My approach to this was to tokenize input into any `Int`, `Double`, specific keywords (e.g. reps, mins), and 'other character groups separated by whitespace', and then use the relative order to chunk associated tokens together (e.g. Int + "reps"), while keeping track of the ranges so that the UI can highlight selected item. 

Probably I can do the above with a regular expression, but because my input is so short this text-preprocessing isn't causing any bottleneck in performance so I'm happy with the readability I get from not using regular expression (obviously biased since I wrote mustard, and also not familiar with regex).

**A2**
For the CSS parser, I don't think that Mustard would be a good match because it doesn't support any sort of nested matching (although I suppose you *could* create a `TokenizerType` that performs a recursive match, I think with the size of documents you're using it probably be slow).

And in terms of regular expression vs scanner... I would approach it using a scanner, simply because I'm not that comfortable with regular expressions.

I just did a search to look at CSS syntax examples (that's how unfamiliar I am with CSS) and noticed that at the moment CSS doesn't allow for rules to be nested, but a [proposed spec](http://tabatkins.github.io/specs/css-nesting/) might allow for this in the future. My gut feeling is that when things start nesting, regular expressions might not be the best approach.

**Comment by eonist** [comment]
If you built your own Tokenizer Lib. I think you could understand RegEx. RegEx is pretty simple. It's the nuances that will trip you up though. Miss a char and it doesn't work. My approach is to keep vast amounts of examples around, so that I can jump into the RegEx language by reviewing the examples. Also RegEx differs slightly for every language but keeps the core rules. 

``"I have a mystical belief that regular expressions can probably do just about anything".`` What I do know is that RegEx is not used for parsing HTML etc. As making a custom traverser is more optimised in terms of speed. But also more complicated to build. The reason I use RegEx for parsing is that its pretty fast, and its easy to add additional functionality down the line. Or port to other languages. Custom traversers on the other quickly lose the "ease-of-use" factor in terms of adding custom functionality. 

Thinking of ease of use: This came to mind: https://github.com/VerbalExpressions/SwiftVerbalExpressions

Looking at the code of VerbalExpression...It's a wrapper around RegEx. Not a very big one either. Pretty cool!

Maybe mustard could be that to? Looking at your benchmarks it could probably speed things up. Speed isn't needed now, but could be in the future?

One thing that has always  attracted me about RegEx is the puzzle aspect of it. Like a challenge. But it definitely need to be more human readable. 

That said I definitely think dissecting the written language will be 🔑 in the future. The AI-wave and all that. 🌭 seems like a fun project in that regard.

**Comment by mathewsanders** [comment]
Yeah... the nuances are what get me. Simple to learn, difficult to master!

I made a decision a couple PR's back that I wasn't going to make speed a priority, but having said that I don't want Mustard to be *slow*. I made some immediate improvements to performance, and need to update the benchmark page because the latest release is actually a bit faster than the benchmark says, and it's something that I do want to work on in future releases :) 

For me the priority over speed is to be more expressive, that verbal expressions project you linked to is a great example (and really cool project).

I'm really curious to see where the Swift team takes regular expressions in future versions, hopefully as the language evolves regex will become more first class citizens.

And I agree with your hunch about the future 🔑, I think that text-driven interfaces is a really interesting area to explore and have a lot to offer.
